eduardProject/app/resume/__init__.py
from flask import Blueprint

resume_bp = Blueprint('resume', __name__, template_folder='templates/resume', static_folder='static', static_url_path='resume/static')

from . import views

eduardProject/app/resume/views.py
import os
from flask import render_template, redirect, request, abort
from datetime import datetime
from . import resume_bp

my_skills = ["Python", "HTML", "CSS", "JS"]

@resume_bp.route('/')
def main():
    OS = os.environ.get('OS', 'Unknown')
    u_agent = request.user_agent
    time = datetime.now().strftime("%H:%M")
    return render_template('main.html', u_agent=u_agent, time=time, OS=OS)

@resume_bp.route('/l_and_s')
def licenses_and_certifications():
    return render_template('L&S.html')

@resume_bp.route('/skills/<int:id>')
@resume_bp.route('/skills')
def skills(id=None):
    if id is not None:
        if id > len(my_skills):
            abort(404)
        else:
            index = id - 1
            skill = my_skills[index]
            return render_template('skill.html', skill=skill)
    else:
        return render_template('skills.html', my_skills=my_skills)

eduardProject/app/resume/templates/resume/L&S.html
{% extends 'base.html' %}
{% block title %}Licenses & certifications{% endblock %}
{% block content %}
    <div class="container overflow-hidden text-center">
      <div class="row gx-5">
        <div class="col">
         <div class="p-3">
             <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Certificate name</th>
                      <th scope="col">Issued by</th>
                      <th scope="col">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr class="table-primary">
                      <th scope="row">IBM Full Stack Software Developer Specialization</th>
                      <td>Coursera</td>
                      <td>Sep 2023</td>
                    </tr>
                    <tr class="table-secondary">
                      <th scope="row">JavaScript Essentials 1 (JSE)</th>
                      <td>Cisco Networking Academy</td>
                      <td>Dec 2022</td>
                    </tr>
                    <tr class="table-success">
                      <th scope="row">PCAP - Programming Essentials in Python</th>
                      <td>Cisco Networking Academy</td>
                      <td>Dec 2022</td>
                    </tr>
                    <tr class="table-danger">
                      <th scope="row">CPA - Programming Essentials in C++</th>
                      <td>Cisco Networking Academy</td>
                      <td>Jun 2022</td>
                    </tr>
                    <tr class="table-warning">
                      <th scope="row">NDG Linux Essentials</th>
                      <td>Cisco Networking Academy</td>
                      <td>Jun 2022</td>
                    </tr>
                    <tr class="table-info">
                      <th scope="row">CLA - Programming Essentials in C</th>
                      <td>Cisco Networking Academy</td>
                      <td>Mar 2022</td>
                    </tr>
                  </tbody>
             </table>
         </div>
        </div>
      </div>
    </div>
{% endblock %}

eduardProject/app/resume/templates/resume/main.html
{% extends 'base.html' %}
{% block title %}Portfolio{% endblock %}
{% block content %}
    <div class="container overflow-hidden text-center">
      <div class="row gx-5">
        <div class="col">
         <div class="p-3">
             <blockquote class="blockquote">
                 <img src="{{ url_for('resume.static', filename='imgs/new_pic2.png') }}" class="card-img-top img_pic" alt="...">
                 <h2>EDUARD BRYLIUK</h2>
                  <p class="mb-0">Passionate about learning and excited to utilize academic knowledge in a professional setting.</p>
              </blockquote>
             <figcaption class="blockquote-footer">
                <cite title="Source Title">Student, Developer Beginner</cite>
              </figcaption>
         </div>
        </div>
      </div>
    </div>

    <div class="container text-center">
      <div class="row g-0">
        <div class="col">
         <div class="p-3">
             <a href=""><p>LinkedIn</p></a>
             <p>Some_test_mail@gmail.com</p>
         </div>
        </div>
        <div class="col">
          <div class="p-3">
              <a href=""><p>GitHub</p></a>
              <p>+380-45-259-54-78</p>
          </div>
        </div>
      </div>
    </div>

    <div class="container text-center">
      <div class="row g-0">
        <div class="col">
         <div class="p-3">
             <h3>Write me if you interested in cooperation or want to give me job</h3>
             <form>
              <fieldset>
                <div class="form-group">
                  <label for="exampleInputEmail1" class="form-label mt-4">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                  <label for="exampleTextarea" class="form-label mt-4">Print your massage</label>
                  <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
                </div>
                <div class="form-group">
                  <label for="formFile" class="form-label mt-4">Send me file or something :)</label>
                  <input class="form-control" type="file" id="formFile">
                </div>
                  <br>
                  <button type="submit" class="btn btn-primary">Submit</button>
              </fieldset>
             </form>
         </div>
        </div>
      </div>
    </div>
    {% include 'footer.html' %}
{% endblock %}

eduardProject/app/resume/templates/resume/skill.html
{% extends 'base.html' %}
{% block title %}skill{% endblock %}
{% block content %}
    <h1>Skill Display</h1>
    <p>Skill {{ id }}: {{ skill }}</p>
{% endblock %}

eduardProject/app/resume/templates/resume/skills.html
{% extends 'base.html' %}
{% block title %}Skills{% endblock %}
{% block content %}
    <h1>List of Skills</h1>
    <ul>
        {% for skill in my_skills %}
            <a href="{{ url_for('resume.skills', id=loop.index) }}"><li>{{ skill }}</li></a>
        {% endfor %}
    </ul>
    <p>Total Skills: {{ my_skills|length }}</p>
{% endblock %}