eduardProject/app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(100), nullable=False)
    status = db.Column(db.Boolean, default=False)

eduardProject/app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class TodoForm(FlaskForm):
    task = StringField('Task', validators=[DataRequired()])
    submit = SubmitField('Add Task')

eduardProject/app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint('todo', __name__, template_folder='templates', static_folder='static')

from . import views

eduardProject/app/todo/views.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required
from . import todo_bp
from .forms import TodoForm
from .models import Todo
from app import db

@todo_bp.route('/todo', methods=['GET', 'POST'])
@login_required
def todo():
    form = TodoForm()

    if form.validate_on_submit():
        task = form.task.data
        new_todo = Todo(task=task)
        db.session.add(new_todo)
        db.session.commit()
        flash('Task added successfully!', 'success')
        return redirect(url_for('todo.todo'))

    todos = Todo.query.all()
    return render_template('todo/todo.html', form=form, todos=todos)

@todo_bp.route('/todo/update/<int:id>')
@login_required
def update_todo(id):
    todo = Todo.query.get_or_404(id)
    todo.status = not todo.status  # Toggle status
    db.session.commit()
    flash('Task updated successfully!', 'success')
    return redirect(url_for('todo.todo'))

@todo_bp.route('/todo/delete/<int:id>')
@login_required
def delete_todo(id):
    todo = Todo.query.get_or_404(id)
    db.session.delete(todo)
    db.session.commit()
    flash('Task deleted successfully!', 'success')
    return redirect(url_for('todo.todo'))

eduardProject/app/todo/templates/todo/todo.html
{% extends "base.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Todo List</h1>
        <form method="POST" action="{{ url_for('todo.todo') }}" class="mb-4 justify-content-center">
            {{ form.hidden_tag() }}
            <div class="input-group">
                {{ form.task.label(class="input-group-text") }}
                {{ form.task(class="form-control") }}
            </div>
            <div class="mt-2">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
        <table class="table table-danger table-responsive-md mx-auto">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="text-center">Завдання</th>
                    <th scope="col" class="text-center">Статус</th>
                    <th scope="col" class="text-center">Дії</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos %}
                    <tr class="text-center">
                        <th scope="row">{{ todo.id }}</th>
                        <td class="shadow">{{ todo.task }}</td>
                        <td class="{{ 'bg-success' if todo.status else 'bg-primary' }}">
                            {{ 'Завершено' if todo.status else 'В-процесі' }}
                        </td>
                        <td>
                            <a href="{{ url_for('todo.update_todo', id=todo.id) }}" class="btn btn-info btn-sm">Оновити</a>
                            <a href="{{ url_for('todo.delete_todo', id=todo.id) }}" class="btn btn-primary btn-sm">Видалити</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}